"""empty message

Revision ID: 3289cd6af57a
Revises: e2588b844367
Create Date: 2024-12-04 11:30:09.589854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3289cd6af57a'
down_revision: Union[str, None] = 'e2588b844367'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cart', 'address',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('category', 'products_amount')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('products_amount', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.alter_column('cart', 'address',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
