"""empty message

Revision ID: de963a62c35f
Revises: aa3876b4783a
Create Date: 2024-12-04 19:43:28.042037

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de963a62c35f'
down_revision: Union[str, None] = 'aa3876b4783a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('faq',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.execute("""
    INSERT INTO faq (title, text) 
    VALUES
      ('FAQ Title 1', 'This is the content of FAQ 1'),
      ('FAQ Title 2', 'This is the content of FAQ 2'),
      ('FAQ Title 3', 'This is the content of FAQ 3'),
      ('FAQ Title 4', 'This is the content of FAQ 4'),
      ('FAQ Title 5', 'This is the content of FAQ 5'),
      ('FAQ Title 6', 'This is the content of FAQ 6'),
      ('FAQ Title 7', 'This is the content of FAQ 7'),
      ('FAQ Title 8', 'This is the content of FAQ 8'),
      ('FAQ Title 9', 'This is the content of FAQ 9'),
      ('FAQ Title 10', 'This is the content of FAQ 10')
      """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('faq')
    # ### end Alembic commands ###
