# Generated by Django 5.1.4 on 2024-12-05 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0002_faq"),
    ]

    operations = [
        migrations.RenameField(
            model_name="faq",
            old_name="first_name",
            new_name="title",
        ),
    ]
